/********************************************************************
* NonCollisionBG_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NonCollisionBG_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableNonCollisionBG_dict();
extern void G__cpp_setup_inheritanceNonCollisionBG_dict();
extern void G__cpp_setup_typetableNonCollisionBG_dict();
extern void G__cpp_setup_memvarNonCollisionBG_dict();
extern void G__cpp_setup_globalNonCollisionBG_dict();
extern void G__cpp_setup_memfuncNonCollisionBG_dict();
extern void G__cpp_setup_funcNonCollisionBG_dict();
extern void G__set_cpp_environmentNonCollisionBG_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NonCollisionBG.h"
#include "NonCollisionBG.cc"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NonCollisionBG_dictLN_TClass;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TBuffer;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMemberInspector;
extern G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TFile;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TVector3;
extern G__linked_taginfo G__NonCollisionBG_dictLN_TH1F;
extern G__linked_taginfo G__NonCollisionBG_dictLN_NonCollisionBG;
extern G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgR;
extern G__linked_taginfo G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
