//
// File generated by rootcint at Tue Apr 19 18:36:47 2011

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "NonCollisionBG_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void NonCollisionBG_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_NonCollisionBG(void *p = 0);
   static void *newArray_NonCollisionBG(Long_t size, void *p);
   static void delete_NonCollisionBG(void *p);
   static void deleteArray_NonCollisionBG(void *p);
   static void destruct_NonCollisionBG(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::NonCollisionBG*)
   {
      ::NonCollisionBG *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::NonCollisionBG >(0);
      static ::ROOT::TGenericClassInfo 
         instance("NonCollisionBG", ::NonCollisionBG::Class_Version(), "NonCollisionBG.h", 28,
                  typeid(::NonCollisionBG), DefineBehavior(ptr, ptr),
                  &::NonCollisionBG::Dictionary, isa_proxy, 4,
                  sizeof(::NonCollisionBG) );
      instance.SetNew(&new_NonCollisionBG);
      instance.SetNewArray(&newArray_NonCollisionBG);
      instance.SetDelete(&delete_NonCollisionBG);
      instance.SetDeleteArray(&deleteArray_NonCollisionBG);
      instance.SetDestructor(&destruct_NonCollisionBG);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::NonCollisionBG*)
   {
      return GenerateInitInstanceLocal((::NonCollisionBG*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NonCollisionBG*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *NonCollisionBG::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *NonCollisionBG::Class_Name()
{
   return "NonCollisionBG";
}

//______________________________________________________________________________
const char *NonCollisionBG::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::NonCollisionBG*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int NonCollisionBG::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::NonCollisionBG*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void NonCollisionBG::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::NonCollisionBG*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *NonCollisionBG::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::NonCollisionBG*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void NonCollisionBG::Streamer(TBuffer &R__b)
{
   // Stream an object of class NonCollisionBG.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(NonCollisionBG::Class(),this);
   } else {
      R__b.WriteClassBuffer(NonCollisionBG::Class(),this);
   }
}

//______________________________________________________________________________
void NonCollisionBG::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class NonCollisionBG.
      TClass *R__cl = ::NonCollisionBG::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*file_COSMIC", &file_COSMIC);
      R__insp.Inspect(R__cl, R__parent, "*file_PHOTON", &file_PHOTON);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_NonCollisionBG(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::NonCollisionBG : new ::NonCollisionBG;
   }
   static void *newArray_NonCollisionBG(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::NonCollisionBG[nElements] : new ::NonCollisionBG[nElements];
   }
   // Wrapper around operator delete
   static void delete_NonCollisionBG(void *p) {
      delete ((::NonCollisionBG*)p);
   }
   static void deleteArray_NonCollisionBG(void *p) {
      delete [] ((::NonCollisionBG*)p);
   }
   static void destruct_NonCollisionBG(void *p) {
      typedef ::NonCollisionBG current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::NonCollisionBG

/********************************************************
* NonCollisionBG_dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableNonCollisionBG_dict();

extern "C" void G__set_cpp_environmentNonCollisionBG_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("NonCollisionBG.h");
  G__add_compiledheader("NonCollisionBG.cc");
  G__cpp_reset_tagtableNonCollisionBG_dict();
}
#include <new>
extern "C" int G__cpp_dllrevNonCollisionBG_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* NonCollisionBG */
static int G__NonCollisionBG_dict_268_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NonCollisionBG* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NonCollisionBG[n];
     } else {
       p = new((void*) gvp) NonCollisionBG[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NonCollisionBG;
     } else {
       p = new((void*) gvp) NonCollisionBG;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_NonCollisionBG));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((NonCollisionBG*) G__getstructoffset())->sigmaRCosmic(
(float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2]), (float*) G__int(libp->para[3])
, (float*) G__int(libp->para[4]), (float*) G__int(libp->para[5])
, (float*) G__int(libp->para[6]), (float*) G__int(libp->para[7])
, (float*) G__int(libp->para[8]), (int) G__int(libp->para[9])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((NonCollisionBG*) G__getstructoffset())->fisherCosmic3((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((NonCollisionBG*) G__getstructoffset())->fisherCosmic2((float) G__double(libp->para[0]), (float) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 7:
      G__letint(result7, 103, (long) ((NonCollisionBG*) G__getstructoffset())->isHEHalo(
(float) G__double(libp->para[0]), (int) G__int(libp->para[1])
, (float*) G__int(libp->para[2]), (float*) G__int(libp->para[3])
, (float*) G__int(libp->para[4]), (float*) G__int(libp->para[5])
, (bool) G__int(libp->para[6])));
      break;
   case 6:
      G__letint(result7, 103, (long) ((NonCollisionBG*) G__getstructoffset())->isHEHalo((float) G__double(libp->para[0]), (int) G__int(libp->para[1])
, (float*) G__int(libp->para[2]), (float*) G__int(libp->para[3])
, (float*) G__int(libp->para[4]), (float*) G__int(libp->para[5])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 6:
      G__letint(result7, 103, (long) ((NonCollisionBG*) G__getstructoffset())->isCSCHalo((float) G__double(libp->para[0]), (int) G__int(libp->para[1])
, (float*) G__int(libp->para[2]), (float*) G__int(libp->para[3])
, (float*) G__int(libp->para[4]), (bool) G__int(libp->para[5])));
      break;
   case 5:
      G__letint(result7, 103, (long) ((NonCollisionBG*) G__getstructoffset())->isCSCHalo((float) G__double(libp->para[0]), (int) G__int(libp->para[1])
, (float*) G__int(libp->para[2]), (float*) G__int(libp->para[3])
, (float*) G__int(libp->para[4])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((NonCollisionBG*) G__getstructoffset())->isTrackHalo((float) G__double(libp->para[0]), (int) G__int(libp->para[1])
, (float*) G__int(libp->para[2]), (float*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((NonCollisionBG*) G__getstructoffset())->deltaPhiCSCHalo((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      G__letdouble(result7, 102, (double) ((NonCollisionBG*) G__getstructoffset())->simpleBarrelE2E9((int) G__int(libp->para[0]), *(vector<int>*) libp->para[1].ref
, *(vector<int>*) libp->para[2].ref, *(vector<float>*) libp->para[3].ref
, (int) G__int(libp->para[4])));
      break;
   case 4:
      G__letdouble(result7, 102, (double) ((NonCollisionBG*) G__getstructoffset())->simpleBarrelE2E9((int) G__int(libp->para[0]), *(vector<int>*) libp->para[1].ref
, *(vector<int>*) libp->para[2].ref, *(vector<float>*) libp->para[3].ref));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      G__letint(result7, 103, (long) ((NonCollisionBG*) G__getstructoffset())->isE2E9Spike((int) G__int(libp->para[0]), *(vector<int>*) libp->para[1].ref
, *(vector<int>*) libp->para[2].ref, *(vector<float>*) libp->para[3].ref
, (int) G__int(libp->para[4])));
      break;
   case 4:
      G__letint(result7, 103, (long) ((NonCollisionBG*) G__getstructoffset())->isE2E9Spike((int) G__int(libp->para[0]), *(vector<int>*) libp->para[1].ref
, *(vector<int>*) libp->para[2].ref, *(vector<float>*) libp->para[3].ref));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((NonCollisionBG*) G__getstructoffset())->isTimeSpike(*(vector<float>*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) NonCollisionBG::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NonCollisionBG::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) NonCollisionBG::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      NonCollisionBG::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const NonCollisionBG*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NonCollisionBG*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref, (char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NonCollisionBG*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NonCollisionBG*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NonCollisionBG::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NonCollisionBG::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NonCollisionBG::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__NonCollisionBG_dict_268_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NonCollisionBG::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__NonCollisionBG_dict_268_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   NonCollisionBG* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new NonCollisionBG(*(NonCollisionBG*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_NonCollisionBG));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NonCollisionBG G__TNonCollisionBG;
static int G__NonCollisionBG_dict_268_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NonCollisionBG*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NonCollisionBG*) (soff+(sizeof(NonCollisionBG)*i)))->~G__TNonCollisionBG();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NonCollisionBG*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NonCollisionBG*) (soff))->~G__TNonCollisionBG();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__NonCollisionBG_dict_268_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NonCollisionBG* dest = (NonCollisionBG*) G__getstructoffset();
   *dest = *(NonCollisionBG*) libp->para[0].ref;
   const NonCollisionBG& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* NonCollisionBG */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncNonCollisionBG_dict {
 public:
  G__Sizep2memfuncNonCollisionBG_dict(): p(&G__Sizep2memfuncNonCollisionBG_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncNonCollisionBG_dict::*p)();
};

size_t G__get_sizep2memfuncNonCollisionBG_dict()
{
  G__Sizep2memfuncNonCollisionBG_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceNonCollisionBG_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableNonCollisionBG_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<bool,TVector3> >",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* NonCollisionBG */
static void G__setup_memvarNonCollisionBG(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__NonCollisionBG_dictLN_NonCollisionBG));
   { NonCollisionBG *p; p=(NonCollisionBG*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->file_COSMIC)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TFile),-1,-1,1,"file_COSMIC=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->file_PHOTON)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TFile),-1,-1,1,"file_PHOTON=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarNonCollisionBG_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncNonCollisionBG(void) {
   /* NonCollisionBG */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__NonCollisionBG_dictLN_NonCollisionBG));
   G__memfunc_setup("NonCollisionBG",1376,G__NonCollisionBG_dict_268_0_1, 105, G__get_linked_tagnum(&G__NonCollisionBG_dictLN_NonCollisionBG), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("sigmaRCosmic",1217,G__NonCollisionBG_dict_268_0_2, 102, -1, -1, 0, 10, 1, 1, 0, 
"f - - 0 - Pho_sc_x f - - 0 - Pho_sc_y "
"f - - 0 - Pho_sc_z F - - 0 - CosmicMuon_OuterTrack_InnerPoint_x "
"F - - 0 - CosmicMuon_OuterTrack_InnerPoint_y F - - 0 - CosmicMuon_OuterTrack_InnerPoint_z "
"F - - 0 - CosmicMuon_OuterTrack_InnerPoint_px F - - 0 - CosmicMuon_OuterTrack_InnerPoint_py "
"F - - 0 - CosmicMuon_OuterTrack_InnerPoint_pz i - - 0 - CosmicMuon_n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fisherCosmic3",1298,G__NonCollisionBG_dict_268_0_3, 102, -1, -1, 0, 3, 1, 1, 0, 
"f - - 0 - Photon_Roundness f - - 0 - Photon_Angle "
"f - - 0 - Photon_phHasConversionTracks", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fisherCosmic2",1297,G__NonCollisionBG_dict_268_0_4, 102, -1, -1, 0, 2, 1, 1, 0, 
"f - - 0 - Photon_Roundness f - - 0 - Photon_Angle", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("isHEHalo",749,G__NonCollisionBG_dict_268_0_5, 103, -1, -1, 0, 7, 1, 1, 0, 
"f - - 0 - photonSCphi i - - 0 - nAllHERecHits "
"F - - 0 - HERecHitX F - - 0 - HERecHitY "
"F - - 0 - HERecHitEnergy F - - 0 - HERecHitTime "
"g - - 0 'false' useTime", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("isCSCHalo",825,G__NonCollisionBG_dict_268_0_6, 103, -1, -1, 0, 6, 1, 1, 0, 
"f - - 0 - photonSCphi i - - 0 - nAllCSCSegments "
"F - - 0 - CSCSegmentX F - - 0 - CSCSegmentY "
"F - - 0 - CSCSegmentTime g - - 0 'false' useTime", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("isTrackHalo",1109,G__NonCollisionBG_dict_268_0_7, 103, -1, -1, 0, 4, 1, 1, 0, 
"f - - 0 - photonSCphi i - - 0 - nCosMu "
"F - - 0 - CosTrackX F - - 0 - CosTrackY", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("deltaPhiCSCHalo",1416,G__NonCollisionBG_dict_268_0_8, 102, -1, -1, 0, 3, 1, 1, 0, 
"f - - 0 - photonSCphi f - - 0 - CSCSegmentX "
"f - - 0 - CSCSegmentY", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("simpleBarrelE2E9",1495,G__NonCollisionBG_dict_268_0_9, 102, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - nRH u 'vector<int,allocator<int> >' 'vector<int>' 1 - ietaRH "
"u 'vector<int,allocator<int> >' 'vector<int>' 1 - iphiRH u 'vector<float,allocator<float> >' 'vector<float>' 1 - eRH "
"i - - 0 '100' arrayLimit", "assume first entry is seed! (highest energy)", (void*) NULL, 0);
   G__memfunc_setup("isE2E9Spike",973,G__NonCollisionBG_dict_268_0_10, 103, -1, -1, 0, 5, 1, 1, 0, 
"i - - 0 - nRH u 'vector<int,allocator<int> >' 'vector<int>' 1 - ietaRH "
"u 'vector<int,allocator<int> >' 'vector<int>' 1 - iphiRH u 'vector<float,allocator<float> >' 'vector<float>' 1 - eRH "
"i - - 0 '100' arrayLimit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("isTimeSpike",1127,G__NonCollisionBG_dict_268_0_11, 103, -1, -1, 0, 1, 1, 1, 0, "u 'vector<float,allocator<float> >' 'vector<float>' 1 - tRH", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getEBIntersections",1841,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgR), G__defined_typename("vector<pair<bool,TVector3> >"), 0, 2, 1, 4, 0, 
"u 'TVector3' - 11 - X u 'TVector3' - 11 - P", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("h",104,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 2, 1, 4, 0, 
"d - - 0 - z d - - 1 - length", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OuterEBRho",959,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 1, 1, 4, 0, "d - - 0 - zprimeprime", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("tDCA",316,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 2, 1, 4, 0, 
"u 'TVector3' - 11 - X u 'TVector3' - 11 - P", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("outerIntersectionTs",2029,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 3, 1, 4, 0, 
"u 'TVector3' - 11 - X u 'TVector3' - 11 - P "
"d - - 0 - timeDCA", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("innerIntersectionTs",2010,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__NonCollisionBG_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 3, 1, 4, 0, 
"d - - 0 - R u 'TVector3' - 11 - X "
"u 'TVector3' - 11 - P", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("prob",435,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 2, 1, 4, 0, 
"U 'TH1F' - 0 - h f - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("absDeltaPhi",1089,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 2, 1, 4, 0, 
"f - - 0 - phi1 f - - 0 - phi2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fixPhi",616,(G__InterfaceMethod) NULL, 102, -1, -1, 0, 1, 1, 4, 0, "f - - 0 - phi", "makes range [-pi,pi] to [0,2pi]", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__NonCollisionBG_dict_268_0_21, 85, G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&NonCollisionBG::Class), 0);
   G__memfunc_setup("Class_Name",982,G__NonCollisionBG_dict_268_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&NonCollisionBG::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__NonCollisionBG_dict_268_0_23, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&NonCollisionBG::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__NonCollisionBG_dict_268_0_24, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&NonCollisionBG::Dictionary), 0);
   G__memfunc_setup("IsA",253,G__NonCollisionBG_dict_268_0_25, 85, G__get_linked_tagnum(&G__NonCollisionBG_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__NonCollisionBG_dict_268_0_26, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__NonCollisionBG_dict_268_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__NonCollisionBG_dict_268_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__NonCollisionBG_dict_268_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&NonCollisionBG::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__NonCollisionBG_dict_268_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&NonCollisionBG::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__NonCollisionBG_dict_268_0_31, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&NonCollisionBG::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__NonCollisionBG_dict_268_0_32, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&NonCollisionBG::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("NonCollisionBG", 1376, G__NonCollisionBG_dict_268_0_33, (int) ('i'), G__get_linked_tagnum(&G__NonCollisionBG_dictLN_NonCollisionBG), -1, 0, 1, 1, 1, 0, "u 'NonCollisionBG' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NonCollisionBG", 1502, G__NonCollisionBG_dict_268_0_34, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__NonCollisionBG_dict_268_0_35, (int) ('u'), G__get_linked_tagnum(&G__NonCollisionBG_dictLN_NonCollisionBG), -1, 1, 1, 1, 1, 0, "u 'NonCollisionBG' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncNonCollisionBG_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalNonCollisionBG_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcNonCollisionBG_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__NonCollisionBG_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_NonCollisionBG = { "NonCollisionBG" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_vectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgR = { "vector<pair<bool,TVector3>,allocator<pair<bool,TVector3> > >" , 99 , -1 };
G__linked_taginfo G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<bool,TVector3>,allocator<pair<bool,TVector3> > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableNonCollisionBG_dict() {
  G__NonCollisionBG_dictLN_TClass.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TBuffer.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMemberInspector.tagnum = -1 ;
  G__NonCollisionBG_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TFile.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TVector3.tagnum = -1 ;
  G__NonCollisionBG_dictLN_TH1F.tagnum = -1 ;
  G__NonCollisionBG_dictLN_NonCollisionBG.tagnum = -1 ;
  G__NonCollisionBG_dictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_vectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgR.tagnum = -1 ;
  G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableNonCollisionBG_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TFile);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TVector3);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_TH1F);
   G__tagtable_setup(G__get_linked_tagnum(&G__NonCollisionBG_dictLN_NonCollisionBG),sizeof(NonCollisionBG),-1,263424,(char*)NULL,G__setup_memvarNonCollisionBG,G__setup_memfuncNonCollisionBG);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_vectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__NonCollisionBG_dictLN_reverse_iteratorlEvectorlEpairlEboolcOTVector3gRcOallocatorlEpairlEboolcOTVector3gRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupNonCollisionBG_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupNonCollisionBG_dict()");
  G__set_cpp_environmentNonCollisionBG_dict();
  G__cpp_setup_tagtableNonCollisionBG_dict();

  G__cpp_setup_inheritanceNonCollisionBG_dict();

  G__cpp_setup_typetableNonCollisionBG_dict();

  G__cpp_setup_memvarNonCollisionBG_dict();

  G__cpp_setup_memfuncNonCollisionBG_dict();
  G__cpp_setup_globalNonCollisionBG_dict();
  G__cpp_setup_funcNonCollisionBG_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncNonCollisionBG_dict();
  return;
}
class G__cpp_setup_initNonCollisionBG_dict {
  public:
    G__cpp_setup_initNonCollisionBG_dict() { G__add_setup_func("NonCollisionBG_dict",(G__incsetup)(&G__cpp_setupNonCollisionBG_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initNonCollisionBG_dict() { G__remove_setup_func("NonCollisionBG_dict"); }
};
G__cpp_setup_initNonCollisionBG_dict G__cpp_setup_initializerNonCollisionBG_dict;

